### ISSUE TITLE
Fix: When using test:watch tests fail after saving 

### ISSUE THREAD

**Issue by wovalle** [wovalle/fireorm#104]
If you run `yarn test` everything is ok and green, but when using `test:watch` test start failing after a couple of saves.

So far, these tests are failing: 

```
1) BaseFirestoreRepository
       findById
         must find by id:
     AssertionError: expected { Object (id, name, ...) } to be an instance of Band
      at /Users/willyovalle/dev/own/fireorm/src/BaseFirestoreRepository.spec.ts:163:18
      at step (src/BaseFirestoreRepository.spec.ts:46:23)
      at Object.next (src/BaseFirestoreRepository.spec.ts:27:53)
      at fulfilled (src/BaseFirestoreRepository.spec.ts:18:58)

  2) BaseFirestoreRepository
       findOne
         must return T:
     AssertionError: expected { Object (id, name, ...) } to be an instance of Band
      at /Users/willyovalle/dev/own/fireorm/src/BaseFirestoreRepository.spec.ts:343:28
      at step (src/BaseFirestoreRepository.spec.ts:46:23)
      at Object.next (src/BaseFirestoreRepository.spec.ts:27:53)
      at fulfilled (src/BaseFirestoreRepository.spec.ts:18:58)

  3) BaseFirestoreRepository
       miscellaneous
         should correctly parse geopoints:
     AssertionError: expected { Object (latitude, longitude) } to be an instance of Coordinates
      at /Users/willyovalle/dev/own/fireorm/src/BaseFirestoreRepository.spec.ts:371:44
      at step (src/BaseFirestoreRepository.spec.ts:46:23)
      at Object.next (src/BaseFirestoreRepository.spec.ts:27:53)
      at fulfilled (src/BaseFirestoreRepository.spec.ts:18:58)

  4) BaseFirestoreTransactionRepository
       findById
         must find by id:
     AssertionError: expected { Object (id, name, ...) } to be an instance of Band
      at /Users/willyovalle/dev/own/fireorm/src/BaseFirestoreTransactionRepository.spec.ts:57:20
      at step (src/BaseFirestoreTransactionRepository.spec.ts:46:23)
      at Object.next (src/BaseFirestoreTransactionRepository.spec.ts:27:53)
      at fulfilled (src/BaseFirestoreTransactionRepository.spec.ts:18:58)
```

I had this error before and I remember the fix was related to the way the entities were declared. It seems that in the last PR's a regression was introduced.

**Comment by wovalle** [comment]
It seems that the day I got this error consistently was a fluke rather than the norm. I found a way to reproduce this: Click Save (ctrl + s) twice within a second while running `test:watch` and you'll get this error. It seems that when you save the second time, mocha remove something from memory and the tests fail, but when saving again all the test behave as usual.

I think this is more a problem of mocha than fireorm, so I'll close (for now).
