### ISSUE TITLE
Complex data types couldn't serialize

### ISSUE THREAD

**Issue by sc-cmendoza** [wovalle/fireorm#241]
I had read the documentation about complex data types, however I can't make it works.

I have this:

```typescript

class GeoP{
    latitude: number;
    longitude: number;
}

@Collection()
class SomeModel{
    @Type(() => GeoP)
    geop: GeoP;
}
```

And then I do this:

```typescript
const someGeoPInstance = new GeoP();
someGeoPInstance.latitude = 19.3753433;
someGeoPInstance.longitud = -99.0438667;

const someModelInstance = new SomeModel();
someModelInstance.geop = someGeoPInstance;

getRepository(SomeModel).create(someModelInstance);
```
And then I get this

`Value for argument "data" is not a valid Firestore document. Couldn't serialize object of type "GeoP" (found in field "geop"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).`

Is there something I'm misunderstanding?

**Comment by wovalle** [comment]
Hey! I think tit should work. 

Can you create a minimal repo reproducing the issue so I can check it out?

**Comment by skalashnyk** [comment]
This error is thrown by firestore sdk

```
import * as admin from 'firebase-admin';

class Hello {
}

admin.firestore()
  .collection('foo')
  .doc('test_1')
  .set({
    prop: new Hello()
  })
  .then(console.log)
  .catch(console.error);
```

Output:
```
Error: Value for argument "data" is not a valid Firestore document. Couldn't serialize object of type "Hello" (found in field "prop"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
    at validateUserInput (/Users/skalashnyk/IdeaProjects/clawee-server/src/functions/node_modules/@google-cloud/firestore/build/src/serializer.js:326:15)
    at Object.validateUserInput (/Users/skalashnyk/IdeaProjects/clawee-server/src/functions/node_modules/@google-cloud/firestore/build/src/serializer.js:263:13)
    at validateDocumentData (/Users/skalashnyk/IdeaProjects/clawee-server/src/functions/node_modules/@google-cloud/firestore/build/src/write-batch.js:577:18)
    at WriteBatch.set (/Users/skalashnyk/IdeaProjects/clawee-server/src/functions/node_modules/@google-cloud/firestore/build/src/write-batch.js:243:9)
    at DocumentReference.set (/Users/skalashnyk/IdeaProjects/clawee-server/src/functions/node_modules/@google-cloud/firestore/build/src/reference.js:342:14)
    at Object.<anonymous> (/Users/skalashnyk/IdeaProjects/clawee-server/src/functions/1.test.ts:11:4)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/Users/skalashnyk/.nvm/versions/node/v12.20.1/lib/node_modules/ts-node/src/index.ts:400:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/skalashnyk/.nvm/versions/node/v12.20.1/lib/node_modules/ts-node/src/index.ts:403:12)

```

@wovalle , it can be fixed by serializing entity to plain object before passing to firestore SDK, e.g. `JSON.parse(JSON.stringify(doc))`

**Comment by leandrogehlen** [comment]
This is not necessary.

Please read docs:
https://fireorm.js.org/#/README?id=usage

**Comment by wovalle** [comment]
I'll take a look at your suggestion @skalashnyk

**Comment by wovalle** [comment]
I'll take a look at your suggestion @skalashnyk

**Comment by danieleisenhardt** [comment]
If I'm not mistaken, my pull request (https://github.com/wovalle/fireorm/pull/251) solves this issue.

**Comment by wovalle** [comment]
Does it? My initial idea with this issue was to create a generic mapping between firestore "primitives" and fields in custom models.

Can you provide an example of how would you map a native Reference or GeoPoint with the serialization included in the PR? @danieleisenhardt
