### ISSUE TITLE
TypeError: classTransformer.plainToClass error when trying to find document from DB

### ISSUE THREAD

**Issue by sronmiz** [wovalle/fireorm#288]
Hello!
I'm running my server as Firebase cloud function using NestJS + Express.
When I try to get any kind of document from my DB - I get this error:
```typescript
[0] >  [Nest] 37912  - 12/01/2021, 8:09:06 AM   ERROR [ExceptionsHandler] class_transformer_1.plainToClass is not a function
[0] >  TypeError: class_transformer_1.plainToClass is not a function
[0] >      at BaseFirestoreRepository.AbstractFirestoreRepository._this.extractTFromDocSnap (/Users/ron/private_git/powerdata/apps/api/node_modules/fireorm/lib/src/AbstractFirestoreRepository.js:149:46)
[0] >      at /Users/ron/private_git/powerdata/apps/api/node_modules/fireorm/lib/src/AbstractFirestoreRepository.js:155:101
[0] >      at Array.map (<anonymous>)
[0] >      at AbstractFirestoreRepository._this.extractTFromColSnap (/Users/ron/private_git/powerdata/apps/api/node_modules/fireorm/lib/src/AbstractFirestoreRepository.js:155:69)
[0] >      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
My Entity looks like that:
```typescript
import { Collection, SubCollection, ISubCollection } from 'fireorm';

class Measurement {
  id: string;
  watt: number;
  phase: number;
  deviceId: string;
  timestamp: number;
}

@Collection('users')
export class User {
  id: string;
  houseId: string;

  @SubCollection(Measurement,'measurements')
  measurements?: ISubCollection<Measurement>;
}
```

Thanks and have a good day ^^ :)

**Comment by wovalle** [comment]
This was due a to a breaking change in class-transformer, should be fixed now.

**Comment by sronmiz** [comment]
I have all my versions updated. It's a project from 1 day ago.
